frontend/src/App.js, frontend/src/core/router.js, frontend/src/styles/global.js
=> 프론트엔드 기본 세팅

frontend/package.json, frontend/src/components/common/Nav.js, frontend/src/core/router.js, frontend/src/pages/test.js, frontend/yarn.lock
antd를 사용하여 nav 기본 UI와 router 구현했습니다.
- close #12 
=> Side bar(Nav)  기본 UI 구현

server/src/main/java/com/capstone/server/code/UserErrorCode.java, server/src/main/java/com/capstone/server/dto/UserCreateRequestDto.java, server/src/main/java/com/capstone/server/dto/UserUpdateRequestDto.java, server/src/main/java/com/capstone/server/exception/GlobalExceptionHandler.java, server/src/main/java/com/capstone/server/exception/UserException.java, server/src/main/java/com/capstone/server/model/UserEntity.java, server/src/main/java/com/capstone/server/repository/UserRepository.java, server/src/main/java/com/capstone/server/response/ErrorResponse.java, server/src/main/java/com/capstone/server/response/SuccessResponse.java
폴더 구조 및 환경 세팅, 예시 API 작성
#16 
- [v] New feature (changes which adds functionality)
=> Init: 폴더 구조 및 환경 세팅 #16

.github/workflows/feature.yml, .github/workflows/main.yml, server/.gitignore, server/Dockerfile, server/src/main/resources/application-local.properties
=> github protect test 2

server/src/main/java/com/capstone/server/ServerApplication.java
_github branch protection rule 확인을 휘한 pull request_
- close #27 
=> github branch protection test

README.md
=> Docs : 중간발표 대비 readme.md 내용 추가

index.md
_github page upload를 위해서 Readme.md의 내용과 동일하게 작성하여 githubpage를 올려좋음_
-  #32 
- 
깃허브 페이지 디자인에 대한 토의 필요
디자인 레퍼런스 사이트 : https://jekyllthemes.io/github-pages-themes
=> Docs : 중간평가 대비 github Page 추가

ai/yolov5-crowdhuman/detect.py
- 검출된 이미지에 대한 categories와 annotation을 포함한 JSON 파일 생성 (for 2-stage model)
- close #37 
=> update: create a JSON file for 2-stage model

ai/yolov5-crowdhuman/detect.py
프론트에 이미지를 올릴 것을 고려하여 검출된 이미지 저장 시 종횡비를 맞춰주었음 (3:5)
종횡비를 맞춰주었으나 edge나 corner에 위치한 이미지는 수정되지 않아, 한 번 더 삭제해주는 코드를 작성하였음
- close #41 
=> Update: aspect ratio adjustment

frontend/.eslintrc.js, frontend/package.json, frontend/src/components/addMisingPerson/GuardianInfo.js, frontend/src/components/addMisingPerson/IntelligentSearchInfo.js, frontend/src/components/addMisingPerson/MissingPersonInfo.js, frontend/src/components/addMisingPerson/WearingInfo.js, frontend/src/components/common/SearchBox.js, frontend/src/core/router.js, frontend/src/data/WearingItemMenu.js, frontend/src/pages/AddMissingPersonPage.js
실종 정보 등록 화면 기본 UI 구현
- close #54
=> Feat : 실종 정보 등록 화면 기본 UI 구현

frontend/package.json, frontend/src/components/addMisingPerson/IntelligentSearchInfo.js, frontend/src/components/addMisingPerson/MissingPersonInfo.js, frontend/src/components/common/SearchBox.js, frontend/yarn.lock
실종정보등록 및 실종자 리포트에서 사용될 도로명 주소 검색 기능 구현
- close #60
동작 화면입니다.
=> Feat : 도로명 주소 검색 기능 구현

ai/TextReID/.gitattributes
- clip vocab file add
- close #66 
=> Chore: clip vocabulary add

.vscode/launch.json, server/build.gradle
=> Feat: actuator for health check

ai/TextReID/lib/data/datasets/__init__.py, ai/TextReID/lib/data/datasets/concat_dataset.py, ai/TextReID/lib/data/datasets/cuhkpedes.py
- dataset initialization upload
- close #73 
=> Fix: dataset initialization upload

server/src/main/java/com/capstone/server/code/ErrorCode.java, server/src/main/java/com/capstone/server/controller/MissingPeopleController.java, server/src/main/java/com/capstone/server/service/MissingPeopleService.java
=> Feat : missing-people by id GET API 개발

ai/yolov5-crowdhuman/detect.py
Code refactoring
- close #65 
서버에서 돌린 경우 영상이 많아질수록 시간이 매우 많이 소요됨
검출된 이미지를 필터링 해주는 과정에서 의미없는 시간 소요가 있었음
해당 부분 코드를 수정
=> Chore: run time modify

frontend/src/components/addMisingPerson/GuardianInfo.js, frontend/src/components/addMisingPerson/IntelligentSearchInfo.js, frontend/src/components/addMisingPerson/MissingPersonInfo.js, frontend/src/components/addMisingPerson/WearingInfo.js, frontend/src/components/common/SearchBox.js, frontend/src/data/WearingItemMenu.js, frontend/src/pages/AddMissingPersonPage.js
- PC별 반응형을 위하여 각 요소 사이즈 조정했습니다.
- #80
=> Chore : 실종정보등록 화면 반응형 적용

frontend/src/components/common/ResultView.js, frontend/src/components/missingPersonReport/ReportTabs.js, frontend/src/components/reportIntelligent/IntelligentBasicInfo.js, frontend/src/components/reportIntelligent/IntelligentMap.js, frontend/src/components/reportIntelligent/IntelligentSearchOption.js, frontend/src/components/reportIntelligent/IntelligentSearchResult.js, frontend/src/pages/MissingPersonReportPage.js, frontend/src/styles/global.js
실종자 리포트 페이지의 지능형 탐색 화면 기본 UI 구현
- close #77
=> Feat : 실종자 리포트 화면(지능형탐색) 기본 UI 구현

ai/README.MD, ai/app.py, ai/yolov5_crowdhuman/detect.py
_ 연산 돌린 결과 이미지를 s3에 업로드함._
- close #120 
_추후 방식에따라 s3저장 경로, 파일저장 이름이 변할 수 있음_
=> Feat :  AIServer 이미지 s3업로드 기능 추가

ai/yolov8/run.py
학습을 완료한 YOLOv8 weight 파일과 실행 파일 업로드
- close #115 
주석 상세하게 적어두었으니 주석으로 확인하시면 됩니다.
수정 필요 주석 달린 부분만 경로 수정해서 "run.py" 실행하시면 됩니다.
=> Update: Yolov8 weight upload

frontend/src/components/guardianMain/StepContents.js, frontend/src/components/guardianSelect/AllResultList.js, frontend/src/components/guardianSelect/SelectImgList.js, frontend/src/core/router.js, frontend/src/pages/GuardianMainPage.js, frontend/src/pages/GuardianSelectImgPage.js
디테일, appbar(반응형 고려를 위해) 제외한 기본 UI 구현했습니다.
- close #128 
|기본 화면|이미지 확대 시(preview)|
|---|---|
|<img src="https://github.com/kookmin-sw/capstone-2024-14/assets/84322890/a9f2285c-9e29-4b11-9361-c782923aa2f1" width="200" >|<img src="https://github.com/kookmin-sw/capstone-2024-14/assets/84322890/d3fa376a-1476-4cb1-ad1b-8b066658af1b" width="200" >|
=> Feat : 의뢰인용 이미지 선별 화면 기본 UI 구현

.github/workflows/develop.yml, .github/workflows/main.yml, server/Dockerfile, server/docker-compose.yml
=> Feat: 서버 배포를 위한 develop.yml

ai/README.MD, server/docker-compose.yml, server/src/main/java/com/capstone/server/code/ErrorCode.java, server/src/main/java/com/capstone/server/controller/MissingPeopleController.java, server/src/main/java/com/capstone/server/dto/MissingPeopleCreateRequestDto.java, server/src/main/java/com/capstone/server/dto/MissingPeopleResponseDto.java, server/src/main/java/com/capstone/server/exception/CustomException.java, server/src/main/java/com/capstone/server/model/MissingPeopleEntity.java, server/src/main/java/com/capstone/server/model/enums/Color.java, server/src/main/java/com/capstone/server/model/enums/Gender.java, server/src/main/java/com/capstone/server/model/enums/MissingPeopleType.java, server/src/main/java/com/capstone/server/service/DetectService.java, server/src/main/java/com/capstone/server/service/MissingPeopleService.java, server/src/main/java/com/capstone/server/service/SmsService.java
_파라미터 통일이 안됐던 것들을 합치고, 이미지를 쉽게 가져오기 위해db를 수정하였음_
- close #140 
=> Chore : FrontEnd와 연결하기위한 파라미터 수정

.github/workflows/main.yml, server/src/main/java/com/capstone/server/model/enums/Color.java
=> Fix: main.yml 을 capstone aws 계정 ec2 t2.medium 으로 변경

ai/TextReID/lib/data/metrics/train_evaluation.py, ai/TextReID/lib/engine/train_inference.py, ai/TextReID/lib/engine/trainer.py, ai/TextReID/lib/solver/build.py, ai/TextReID/train_net.py
- visual model layer4 (마지막 레이어) fine tuning을 위한 코드 수정
- textual model (GRU) tuning을 위한 코드 추가
- train 코드에서 성능을 확인하기 위한 inference 코드 추가
- close #146 
- 튜닝 관련 진행 상황은 AI 팀 노션에 내부 페이지 생성 후 정리 중
=> [AI] last layer fine-tuning 및 train 전용 inference code 추가

.github/workflows/develop.yml, .github/workflows/main.yml
=> Fix: set Ubuntu local time in github actions

server/docker-compose.yml, server/src/main/java/com/capstone/server/controller/MissingPeopleController.java, server/src/main/java/com/capstone/server/dto/MissingPeopleDetailResponseDto.java, server/src/main/java/com/capstone/server/dto/MissingPeopleListResponseDto.java, server/src/main/java/com/capstone/server/dto/SearchHistoryListDto.java, server/src/main/java/com/capstone/server/repository/GuardianRepository.java, server/src/main/java/com/capstone/server/repository/MissingPeopleRepository.java, server/src/main/java/com/capstone/server/repository/SearchHistoryRepository.java, server/src/main/java/com/capstone/server/service/MissingPeopleService.java
_실종자 상세정보 및 검색기록 리스트 가져오기 api 추가_
- close #147 
=> Feat : 실종자 상세정보 및 검색기록 리스트 가져오기 api 추가 

server/src/main/java/com/capstone/server/controller/MissingPeopleController.java, server/src/main/java/com/capstone/server/dto/DetectionResultDto.java, server/src/main/java/com/capstone/server/dto/SearchResultDto.java, server/src/main/java/com/capstone/server/exception/CustomException.java, server/src/main/java/com/capstone/server/model/SearchResultEntity.java, server/src/main/java/com/capstone/server/model/enums/SearchResultSortBy.java, server/src/main/java/com/capstone/server/repository/SearchResultRepository.java, server/src/main/java/com/capstone/server/service/DetectService.java, server/src/main/java/com/capstone/server/service/MissingPeopleService.java
_실종자 List 가져오기 api 변경, ai 탐색결과 가져오기 더미 api 생성._
- close #161 
=> Feat : 실종자 List 가져오기 api 변경, ai 탐색결과 가져오기 더미 api 생성

server/src/main/java/com/capstone/server/controller/MissingPeopleController.java, server/src/main/java/com/capstone/server/dataInitializer/CCTVInitializer.java, server/src/main/java/com/capstone/server/dto/DetectionRequestDto.java, server/src/main/java/com/capstone/server/dto/DetectionResultDto.java, server/src/main/java/com/capstone/server/dto/SearchResultDto.java, server/src/main/java/com/capstone/server/model/CCTVEntity.java, server/src/main/java/com/capstone/server/repository/SearchHistoryRepository.java, server/src/main/java/com/capstone/server/repository/SearchResultRepository.java, server/src/main/java/com/capstone/server/service/DetectService.java, server/src/main/java/com/capstone/server/service/MissingPeopleService.java
_더미데이터 말고도 값을 받을 수 있게
step별로 가져오기 추가
cctv정보 추가_
- close #163 
_db갈아엎을때 cctv정보 매번 추가하기 귀찮을거 같아, initializer생성했습니다. properties에서 서버시작할때 데이터 넣을지 말지 설정 가능합니다. @su-hwani  _
=> Feat : 탐색결과 가져오기 api 보충

server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
=> Fix: ProfileUrl original response

server/src/main/java/com/capstone/server/code/ErrorCode.java, server/src/main/java/com/capstone/server/controller/MissingPeopleController.java, server/src/main/java/com/capstone/server/dataInitializer/CCTVInitializer.java, server/src/main/java/com/capstone/server/dto/CCTVDto.java, server/src/main/java/com/capstone/server/model/enums/MissingPeopleSortBy.java, server/src/main/java/com/capstone/server/model/enums/Status.java, server/src/main/java/com/capstone/server/service/DetectService.java, server/src/main/java/com/capstone/server/service/MissingPeopleService.java
=> Fix : 버그수정 및 예외처리 추가 

.github/workflows/main.yml
=> Fix: main.yml change docker-compose.yml download path

server/src/main/java/com/capstone/server/controller/GuardianController.java, server/src/main/java/com/capstone/server/dto/MissingPeopleForGuardianDto.java, server/src/main/java/com/capstone/server/dto/guardian/BetweenPostRequestDto.java, server/src/main/java/com/capstone/server/dto/guardian/DetectionResultForGuardianDto.java, server/src/main/java/com/capstone/server/dto/guardian/MissingPeopleForGuardianDto.java, server/src/main/java/com/capstone/server/model/BetweenEntity.java, server/src/main/java/com/capstone/server/repository/BetweenRepository.java, server/src/main/java/com/capstone/server/service/GuardianService.java
보호자 화면 api 구현 하였습니다.
- close #174 
사용할때 바꼈으면 하는부분 있으면 말씀해주세요 @ancy0
=> Feat : 보호자화면 api 구현

.github/workflows/develop.yml, .github/workflows/main.yml, server/docker-compose.yml, server/src/main/java/com/capstone/server/code/ErrorCode.java, server/src/main/java/com/capstone/server/controller/MissingPeopleController.java, server/src/main/java/com/capstone/server/dataInitializer/CCTVInitializer.java, server/src/main/java/com/capstone/server/dto/CCTVDto.java, server/src/main/java/com/capstone/server/dto/DetectionRequestDto.java, server/src/main/java/com/capstone/server/dto/DetectionResultDto.java, server/src/main/java/com/capstone/server/dto/SearchResultDto.java, server/src/main/java/com/capstone/server/model/CCTVEntity.java, server/src/main/java/com/capstone/server/model/enums/MissingPeopleSortBy.java, server/src/main/java/com/capstone/server/model/enums/Status.java, server/src/main/java/com/capstone/server/repository/SearchHistoryRepository.java, server/src/main/java/com/capstone/server/repository/SearchResultRepository.java, server/src/main/java/com/capstone/server/service/DetectService.java, server/src/main/java/com/capstone/server/service/MissingPeopleService.java
- close #167 
main 은 캡스톤 ec2 사용 중 
develop 은 정수환 ec2 사용 중 
@ancy0 
채영님이 직접 변경하실 일은 없을 것 같지만, 알아두시는 게 좋을 것 같아 공유드립니다! 
Frontend .env 파일 내 api root 는 .env 파일 내 작성된 것과 상관없이, 
github actions secrets 에 있는 FRONTEND_API_ROOT 값으로 덮어씌워집니다. 
현재는 http://localhost:8080 으로 지정된 상태입니다. 
직접 변경하시거나, 추가, 이용 등 하실 필요없지만 알고 계시는 게 좋을 것 같아 말씀드렸습니다. 
=> Feat: Frontend & Server 빌드 및 배포 자동화

ai/TextReID/README.md
- train 코드 수정으로 인한 README의 코드 실행 방법 안내 변경
- close #177 
=> Docs: train 코드 수정에 관한 README 내 실행 방법 안내 변경

frontend/src/components/addMisingPerson/AnnotationData.js, frontend/src/components/addMisingPerson/AnnotationInfo.js, frontend/src/data/WearingItemMenu.js, frontend/src/pages/AddMissingPersonPage.js
실종정보등록 설명 텍스트 추가
- close #158 
- 각 기기별로 설명 gap을 다르게 설정하여 간격유지 했습니다.
=> Feat : 실종 정보 등록 설명 텍스트 추가

.github/workflows/develop.yml, .github/workflows/main.yml
**frontend root api 수정**
- close #179 
=> Fix: Frontend root api path 

server/src/main/java/com/capstone/server/controller/GuardianController.java, server/src/main/java/com/capstone/server/controller/MissingPeopleController.java, server/src/main/java/com/capstone/server/controller/TestController.java, server/src/main/java/com/capstone/server/dto/shortUrl/ShortUrlRequestDto.java, server/src/main/java/com/capstone/server/dto/shortUrl/ShortUrlResponseDto.java, server/src/main/java/com/capstone/server/exception/CustomException.java, server/src/main/java/com/capstone/server/service/DetectService.java, server/src/main/java/com/capstone/server/service/EncryptionService.java, server/src/main/java/com/capstone/server/service/SmsService.java
문자 양식을
Url단축 서비스를 네이버 open api로 변경
사용자 정보 유출 방지를 위해 암호화 및 쿠키를 사용하여 실종자 id 암호화
=> Feat :  url단축 서비스 변경, 사용자 정보 암호화 진행

server/docker-compose.yml, server/src/main/java/com/capstone/server/controller/MissingPeopleController.java, server/src/main/java/com/capstone/server/controller/TestController.java, server/src/main/java/com/capstone/server/service/SmsService.java
=> FIX: url 수정 

server/src/main/java/com/capstone/server/dto/guardian/MissingPeopleForGuardianDto.java
=> fix : 보호자 페이지 쿼리 한국어로 가게 수정

frontend/package.json, frontend/src/core/api/index.js, frontend/src/core/cookie.js, frontend/yarn.lock, server/src/main/java/com/capstone/server/controller/GuardianController.java
react-cookie를 통해 실종자 authToken 받기
- close #192 
=> Feat : 실종자 쿠키 받아오기

.vscode/settings.json, server/build.gradle, server/src/main/java/com/capstone/server/config/OpenAiConfig.java, server/src/main/java/com/capstone/server/controller/ChatGPTController.java, server/src/main/java/com/capstone/server/dto/ChatGPTRequest.java, server/src/main/java/com/capstone/server/dto/ChatGPTResponse.java, server/src/main/java/com/capstone/server/dto/Message.java, server/src/main/java/com/capstone/server/service/ChatGPTService.java
- close #208 
아직 수정된 내용 반영 안함
properties 수정됨 노션 확인
=> Feat: ChatGPT API Service

server/src/main/java/com/capstone/server/controller/MissingPeopleController.java, server/src/main/java/com/capstone/server/service/KafkaConsumerService.java, server/src/main/java/com/capstone/server/service/KafkaProducerService.java
=> Feat: Kafka For Second AI model

ai/TextReID/lib/config/defaults.py, ai/TextReID/lib/data/metrics/evaluation.py, ai/TextReID/test_net.py
- top k 개수 args로 받아오는 방식으로 수정
- close #217 
=> Update: TOP K set by giving argument

ai/imageSearch/imgSearch.py
이미지 유사도 모델 수정본 업로드
BE용 결과 저장 완료
- close #207 
실행 코드
`python imgSearch.py --data_path "YOLO저장폴더 path" --topk 유사후보개수(추천 20) --query "쿼리이미지 path"`
=> Update: Modified image similarity model

ai/imageSearch/imgSearch_server.py
테스트용 시각화코드 삭제 후 서버용 이미지 유사도 모델 구현
- close #221 
=> Update: Modified image similarity model for server

server/src/main/java/com/capstone/server/controller/MissingPeopleController.java, server/src/main/java/com/capstone/server/dto/detectionResult/DetectionResultDetailDto.java, server/src/main/java/com/capstone/server/repository/BetweenRepository.java, server/src/main/java/com/capstone/server/repository/SearchHistoryRepository.java, server/src/main/java/com/capstone/server/service/DetectService.java, server/src/main/java/com/capstone/server/service/SearchHistoryService.java, server/src/main/java/com/capstone/server/service/SearchResultService.java
리포트 메인에서 보여줄 이미지 수정 (가장 먼저돌린 탐색으로)
지능형 탐색 결과 리스트창 -> 1차탐색만 뜬다고 생각
지능형 탐색 버튼 있는거 -> 1차탐색만
=> fix : api수정

server/src/main/java/com/capstone/server/dto/ChatGPTRequest.java, server/src/main/java/com/capstone/server/dto/MissingPeopleCreateRequestDto.java, server/src/main/java/com/capstone/server/model/CCTVEntity.java, server/src/main/java/com/capstone/server/model/MissingPeopleDetailEntity.java, server/src/main/java/com/capstone/server/model/MissingPeopleEntity.java, server/src/main/java/com/capstone/server/model/SearchHistoryEntity.java, server/src/main/java/com/capstone/server/service/ChatGPTService.java
=> Fix: model Entity 수정 & chatgpt query 수정

server/src/main/java/com/capstone/server/config/KafkaConsumerConfig.java, server/src/main/java/com/capstone/server/config/KafkaProducerConfig.java, server/src/main/java/com/capstone/server/controller/CCTVController.java, server/src/main/java/com/capstone/server/controller/GuardianController.java, server/src/main/java/com/capstone/server/controller/MissingPeopleController.java, server/src/main/java/com/capstone/server/dto/KafkaDto.java, server/src/main/java/com/capstone/server/dto/StepDetailDto.java, server/src/main/java/com/capstone/server/dto/StepDto.java, server/src/main/java/com/capstone/server/repository/CCTVRepository.java, server/src/main/java/com/capstone/server/service/DetectService.java, server/src/main/java/com/capstone/server/service/KafkaConsumerService.java, server/src/main/java/com/capstone/server/service/KafkaProducerService.java, server/src/main/java/com/capstone/server/service/MissingPeopleService.java, server/src/main/java/com/capstone/server/service/SmsService.java
=> Feat: Kafka second model test success

ai/app.py, server/src/main/java/com/capstone/server/controller/MissingPeopleController.java, server/src/main/java/com/capstone/server/dto/MapCCTV.java, server/src/main/java/com/capstone/server/repository/BetweenRepository.java, server/src/main/java/com/capstone/server/repository/SearchResultRepository.java, server/src/main/java/com/capstone/server/service/BetweenService.java, server/src/main/java/com/capstone/server/service/SearchResultService.java
get all marker first step and second step
상호작용단계 추가 완료@ancy0 
=> feat : get all marker first step,between and second step

server/src/main/java/com/capstone/server/service/KafkaConsumerService.java
=> Feat: AI Second result save

server/src/main/java/com/capstone/server/config/KafkaConsumerConfig.java, server/src/main/java/com/capstone/server/config/KafkaProducerConfig.java, server/src/main/java/com/capstone/server/controller/CCTVController.java, server/src/main/java/com/capstone/server/controller/GuardianController.java, server/src/main/java/com/capstone/server/controller/MissingPeopleController.java, server/src/main/java/com/capstone/server/dto/KafkaDto.java, server/src/main/java/com/capstone/server/service/KafkaConsumerService.java, server/src/main/java/com/capstone/server/service/KafkaProducerService.java, server/src/main/java/com/capstone/server/service/MissingPeopleService.java
=> Fix: server error

server/src/main/java/com/capstone/server/controller/MissingPeopleController.java, server/src/main/java/com/capstone/server/service/SearchResultService.java
마커 가져오기 버그 변경 및 응답수정
- close #238
=> fix : 버그수정 및 응답 변경

frontend/src/components/addMisingPerson/AnnotationData.js, frontend/src/components/addMisingPerson/GuardianInfo.js, frontend/src/data/WearingItemMenu.js
실종정보 등록 추가 설명 텍스트 수정
- close #190
=> Chore : 실종정보 등록 추가 설명 텍스트 수정

.github/workflows/develop.yml, .github/workflows/main.yml
=> Fix: github actions workflow Frontend Env

server/src/main/java/com/capstone/server/service/DetectService.java, server/src/main/java/com/capstone/server/service/KafkaConsumerService.java
=> fix : 2차 탐색 종료 시 단계 수색으로 전환

server/src/main/java/com/capstone/server/controller/MissingPeopleController.java, server/src/main/java/com/capstone/server/model/enums/Color.java, server/src/main/java/com/capstone/server/service/BetweenService.java, server/src/main/java/com/capstone/server/service/DetectService.java, server/src/main/java/com/capstone/server/service/SearchResultService.java
탐색기록 Id로 마커띄우기 추가
- close #252
=> Feature : 탐색기록 Id로 마커띄우기 추가

server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
=> Fix : mapposition 버그수정

frontend/src/components/addMisingPerson/MissingPersonInfo.js, frontend/src/components/addMisingPerson/WearingInfo.js, frontend/src/data/WearingItemMenu.js, frontend/src/pages/AddMissingPersonPage.js
- 착장정보 아이템 추가
- 실종자 유형 토글 추가
- 입력 및 선택 없는 경우에 대한 처리
- close #227 
=> Chore : 실종 정보 등록 토글 수정 및 추가

server/src/main/java/com/capstone/server/repository/CCTVRepository.java, server/src/main/java/com/capstone/server/service/CCTVService.java, server/src/main/java/com/capstone/server/service/MissingPeopleService.java
=> Hot fix : Cctv 가져오기 로직 버그수정

frontend/src/components/missingPersonReport/IntelligentReportList.js, frontend/src/components/reportIntelligent/IntelligentSearchBox.js, frontend/src/components/reportIntelligent/IntelligentSearchOption.js
=> Chore : 경찰 화면 반응형 수정

README.md, server/src/main/java/com/capstone/server/service/ChatGPTService.java
- README 관련 문서 링크 업데이트 반영
- close #257 
=> Merge: README 문서 수정 업데이트 반영

server/src/main/java/com/capstone/server/repository/SearchHistoryRepository.java, server/src/main/java/com/capstone/server/service/DetectService.java, server/src/main/java/com/capstone/server/service/SearchHistoryService.java
=> fix :  스탭돌아가는 버그수정 및 알고리즘 수정#279

server/src/main/java/com/capstone/server/service/SearchHistoryService.java
=> Fix : step 버그수정

server/src/main/java/com/capstone/server/controller/GuardianController.java, server/src/main/java/com/capstone/server/service/GuardianService.java
=> fix : 상호작용단계 막아놓기

README.md
- README 소개영상 업데이트
- close #277 
=> Docs: README 소개 영상 업데이트

.gitignore, server/src/main/java/com/capstone/server/config/WebConfig.java
=> Fix : cors 수정 #288

server/src/main/java/com/capstone/server/config/WebConfig.java
=> fix : cors에러수정 #288

server/docker-compose.yml
=> Fix: docker server image set TimeZon Asia

server/docker-compose.yml
=> delete: kafka TimeZone

frontend/src/components/common/SearchBox.js
- 시연용 지능형 탐색 범위 제한
- close #300
=> Chore : 시연용 지능형 탐색 범위 제한
